CREATE DATABASE NHOM12_QLBVMB

USE NHOM12_QLBVMB

--TAO TAI KHOAN
CREATE TABLE TAIKHOAN (
	TenDangNhap VARCHAR(20) UNIQUE NOT NULL,
	MatKhau VARCHAR(20),
	chucnang varchar(20)
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY (TenDangNhap)
)


-- 1. TABLE CHUYEN BAY
CREATE TABLE CHUYENBAY (
	MaChuyenBay VARCHAR(10)	NOT NULL,
	MaTuyenBay VARCHAR(10),
	NgayGio SMALLDATETIME,
	ThoiGianBay INT,
	SoLuongGheHang1 INT,
	SoLuongGheHang2 INT,
	CONSTRAINT PK_CHUYENBAY PRIMARY KEY (MaChuyenBay)
)


-- 2. TABLE TUYEN BAY
CREATE TABLE TUYENBAY (
	MaTuyenBay VARCHAR(10) NOT NULL,
	SanBayDi VARCHAR(10),
	SanBayDen VARCHAR(10),
	CONSTRAINT PK_TUYENBAY PRIMARY KEY (MaTuyenBay)
)

-- 3. TABLE CHITIETCHUYENBAY
CREATE TABLE CHITIETCHUYENBAY (
	MaChuyenBay VARCHAR(10) NOT NULL,
	MaSanBayTrungGian VARCHAR(10) NOT NULL,
	STT varchar(10)
	CONSTRAINT PK_CHITIETCHUYENBAY PRIMARY KEY (MaChuyenBay, MaSanBayTrungGian)
)


-- 4. TABLE SANBAYTRUNGGIAN
CREATE TABLE SANBAYTRUNGGIAN(
	MaSanBayTrungGian VARCHAR(10) NOT NULL,
	TenSanBay NVARCHAR(50),
	ThoiGianDung INT,
	GhiChu NVARCHAR(100),
	CONSTRAINT PK_SANBAYTRUNGGIAN PRIMARY KEY (MaSanBayTrungGian)
)


-- 5. TABLE TINH TRANG VE
CREATE TABLE TINHTRANGVE (
	MaTinhTrangVe VARCHAR(10) NOT NULL,
	MaChuyenBay VARCHAR(10),
	MaHangVe VARCHAR(10),
	SoGheTrong INT,
	SoGheDat INT,
	CONSTRAINT PK_TINHTRANGVE PRIMARY KEY (MaTinhTrangVe)
)

-- 6. TABLE DON GIA
CREATE TABLE DONGIA (
	MaDonGia VARCHAR(10) NOT NULL,
	MaChuyenBay VARCHAR(10),
	DonGia FLOAT,
	CONSTRAINT PK_DONGIA PRIMARY KEY (MaDonGia)
)

-- 7. TABLE SAN BAY
CREATE TABLE SANBAY (
	MaSanBay VARCHAR(10) NOT NULL,
	TenSanBay NVARCHAR(50),
	CONSTRAINT PK_SANBAY PRIMARY KEY (MaSanBay)
)

-- 8. TABLE HANH KHACH 
CREATE TABLE HANHKHACH (
	MaHanhKhach VARCHAR(10) NOT NULL,
	TenHanhKhach NVARCHAR(50),
	CMND VARCHAR(12),
	DienThoai VARCHAR(10),
	CONSTRAINT PK_HANHKHACH PRIMARY KEY (MaHanhKhach)
)

-- 9. TABLE VE CHUYEN BAY
CREATE TABLE VECHUYENBAY (
	MaVe VARCHAR(10) NOT NULL,
	MaChuyenBay VARCHAR(10),
	MaHangVe VARCHAR(10),
	MaHanhKhach VARCHAR(10),
	GiaTien FLOAT,
	CONSTRAINT PK_VECHUYENBAY PRIMARY KEY (MaVe)
)

-- 10. TABLE HANG VE
CREATE TABLE HANGVE (
	MaHangVe VARCHAR(10) NOT NULL,
	TenHangVe NVARCHAR(50),
	CONSTRAINT PK_HANGVE PRIMARY KEY (MaHangVe)
)

-- 11. TABLE CT_DOANHTHUTHANG
CREATE TABLE CT_DOANHTHUTHANG (
	MaCTDTThang VARCHAR(10) NOT NULL,
	MaDoanhThuThang VARCHAR(10),
	MaChuyenBay VARCHAR(10),
	SoVe INT,
	TyLe FLOAT,
	DoanhThu FLOAT,
	CONSTRAINT PK_CTDOANHTHUTHANG PRIMARY KEY (MaCTDTThang)
)

-- 12. TABLE DOANH THU THANG
CREATE TABLE DOANHTHUTHANG (
	MaDoanhThuThang VARCHAR(10) NOT NULL,
	Thang INT,
	MaDoanhThuNam VARCHAR(10),
	SoChuyenBay INT,
	TyLe FLOAT,
	TongDoanhThuThang FLOAT,
	CONSTRAINT PK_DOANHTHUTHANG PRIMARY KEY (MaDoanhThuThang)
)

-- 13. TABLE DOANH THU NAM
CREATE TABLE DOANHTHUNAM (
	MaDoanhThuNam VARCHAR(10) NOT NULL,
	Nam	INT,
	TongDoanhThuNam FLOAT,
	CONSTRAINT PK_DOANHTHUNAM PRIMARY KEY (MaDoanhThuNam)
)

-- 14. TABLE PHIEU DAT CHO
CREATE TABLE PHIEUDATCHO (
	MaPhieuDat VARCHAR(10) NOT NULL,
	MaChuyenBay VARCHAR(10),
	MaHanhKhach VARCHAR(10),
	MaHangVe VARCHAR(10),
	GiaTien FLOAT,
	NgayDat SMALLDATETIME,
	CONSTRAINT PK_PHIEUDATCHO PRIMARY KEY (MaPhieuDat)
)

-- 15. TABLE THAM SO
CREATE TABLE THAMSO (
	TGBayToiThieu INT,
	TGDungToiThieu INT,
	TGDungToiDa INT,
	TGChamNhatDatVe INT,
	TGChamNhatHuyVe INT
)
insert into THAMSO values(30,10,20,1,2);


-------------------- CREATE FOREIGN KEY ----------------------------------------------
ALTER TABLE TINHTRANGVE ADD CONSTRAINT FK_TINHTRANGVE_CHUYENBAY FOREIGN KEY (MaChuyenBay) REFERENCES CHUYENBAY(MaChuyenBay)
ALTER TABLE VECHUYENBAY ADD CONSTRAINT FK_VECHUYENBAY_CHUYENBAY FOREIGN KEY (MaChuyenBay) REFERENCES CHUYENBAY(MaChuyenBay)
ALTER TABLE PHIEUDATCHO ADD CONSTRAINT FK_PHIEUDATCHO_CHUYENBAY FOREIGN KEY (MaChuyenBay) REFERENCES CHUYENBAY(MaChuyenBay)
ALTER TABLE CT_DOANHTHUTHANG ADD CONSTRAINT FK_CTDOANHTHUTHANG_CHUYENBAY FOREIGN KEY (MaChuyenBay) REFERENCES CHUYENBAY(MaChuyenBay)
--ALTER TABLE CTCHUYENBAY ADD CONSTRAINT FK_CTCHUYENBAY_CHUYENBAY FOREIGN KEY (MaChuyenBay) REFERENCES CHUYENBAY(MaChuyenBay)

ALTER TABLE TUYENBAY ADD CONSTRAINT FK_TUYENBAYSANBAYDI_SANBAY FOREIGN KEY (SanBayDi) REFERENCES SANBAY(MaSanBay)
ALTER TABLE TUYENBAY ADD CONSTRAINT FK_TUYENBAYSANBAYDEN_SANBAY FOREIGN KEY (SanBayDen) REFERENCES SANBAY(MaSanBay)

ALTER TABLE CHUYENBAY ADD CONSTRAINT FK_CHUYENBAY_TUYENBAY FOREIGN KEY (MaTuyenBay) REFERENCES TUYENBAY(MaTuyenBay)
ALTER TABLE DONGIA ADD CONSTRAINT FK_DONGIA_CHUYENBAY FOREIGN KEY (MaChuyenBay) REFERENCES CHUYENBAY(MaChuyenBay)

--sanbay trung gian
ALTER TABLE CHITIETCHUYENBAY ADD CONSTRAINT FK_sanbaytrunggian foreign key(MASANBAYTRUNGGIAN) references SANBAYTRUNGGIAN(MASANBAYTRUNGGIAN)
ALTER TABLE CHITIETCHUYENBAY ADD CONSTRAINT FK_sanbaychuyenbay foreign key(MaChuyenBay) references CHUYENBAY(MaChuyenBay)

ALTER TABLE SANBAYTRUNGGIAN ADD CONSTRAINT FK_SBTG_SANBAY FOREIGN KEY (MaSanBayTrungGian) REFERENCES SANBAY(MaSanBay)

ALTER TABLE TINHTRANGVE ADD CONSTRAINT FK_TINHTRANGVE_HANGVE FOREIGN KEY (MaHangVe) REFERENCES HANGVE(MaHangVe)
ALTER TABLE VECHUYENBAY ADD CONSTRAINT FK_VECHUYENBAY_HANGVE FOREIGN KEY (MaHangVe) REFERENCES HANGVE(MaHangVe)
ALTER TABLE PHIEUDATCHO ADD CONSTRAINT FK_PHIEUDATCHO_HANGVE FOREIGN KEY (MaHangVe) REFERENCES HANGVE(MaHangVe)

ALTER TABLE VECHUYENBAY ADD CONSTRAINT FK_VECHUYENBAY_HANHKHACH FOREIGN KEY (MaHanhKhach) REFERENCES HANHKHACH(MaHanhKhach)
ALTER TABLE PHIEUDATCHO ADD CONSTRAINT FK_PHIEUDATCHO_HANHKHACH FOREIGN KEY (MaHanhKhach) REFERENCES HANHKHACH(MaHanhKhach)

ALTER TABLE DOANHTHUTHANG ADD CONSTRAINT FK_DOANHTHUTHANG_DOANHTHUNAM FOREIGN KEY (MaDoanhThuNam) REFERENCES DOANHTHUNAM(MaDoanhThuNam)
ALTER TABLE CT_DOANHTHUTHANG ADD CONSTRAINT FK_CTDOANHTHUTHANG_DOANHTHUTHANG FOREIGN KEY (MaDoanhThuThang) REFERENCES DOANHTHUTHANG(MaDoanhThuThang)

SET DATEFORMAT DMY

insert into taikhoan values('thang','12345','quanly')
insert into taikhoan values('hanh','12345','nhanvien')
--------- INSERT DATA -----------------------
-- 4. SAN BAY
INSERT INTO SANBAY (MaSanBay, TenSanBay) VALUES
('HN', 'Noi Bai'),
('HCM', 'Tan Son Nhat'),
('DN', 'Da Nang'),
('QN', 'Van Don'),
('HP', 'Cat Bi'),
('CT', 'Can Tho');

-- 2. TUYEN BAY


-- insert san bay trung gian

insert into SANBAYTRUNGGIAN values('HN', 'Noi Bai', 15,'chuyen bay nhanh')
insert into SANBAYTRUNGGIAN values('HCM', 'Tan Son Nhat', 18,'chuyen bay binh thuong')
insert into SANBAYTRUNGGIAN values('DN', 'Da Nang', 20,'chuyen bay nhanh')
insert into SANBAYTRUNGGIAN values('QN', 'Van Don', 14,'chuyen bay cham')
insert into SANBAYTRUNGGIAN values('HP', 'Cat Bi', 12,'chuyen bay nhanh')
insert into SANBAYTRUNGGIAN values('CT', 'Can Tho', 17,'chuyen bay cham')


INSERT INTO HANGVE (MaHangVe, TenHangVe) VALUES
('HV1',N'Ghế hạng Thươnng gia (Business Class)'),
('HV2',N'Ghế hạng Phổ thông (Economy Class)');



